//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericPaymentService.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int Id { get; set; }
        public string TransactionId { get; set; }
        public decimal Amount { get; set; }
        public string PaymentRequest { get; set; }
        public string ProductType { get; set; }
        public bool Paid { get; set; }
        public bool Notified { get; set; }
    }
}
